version: '3.2'
services:
  hydroserver:
    build: .
    ports:
      - '80:80'
    env_file:
      - hs.env
    restart: always
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./log:/mylogs
    container_name: hs_d
